//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutLog.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterContainer : DbContext
    {
        public MasterContainer()
            : base("name=MasterContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerTeamPermissions> PlayerTeamPermissions { get; set; }
        public virtual DbSet<NewsPost> NewsPosts { get; set; }
        public virtual DbSet<WorkoutPost> WorkoutPosts { get; set; }
    }
}
