//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutLog.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NewsPost()
        {
            this.Teams = new HashSet<Team>();
        }
    
        public int Id { get; private set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public System.DateTime PostDate { get; private set; }
    
        public virtual Player Players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
    }
}
