//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutLog.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player(string userId, string firstName, string lastName)
        {
            this.Teams = new HashSet<Team>();
            this.PlayerTeamPermission = new HashSet<PlayerTeamPermissions>();
            this.NewsPost = new HashSet<NewsPost>();
            this.WorkoutPosts = new HashSet<WorkoutPost>();
            this.DateCreated = DateTime.UtcNow;

            this.UserId = userId;
            this.FirstName = firstName;
            this.LastName = lastName;
        }
    
        public int Id { get; private set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [Index(IsUnique = true)]
        public string UserId { get; private set; }
        public System.DateTime DateCreated { get; private set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Team> Teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerTeamPermissions> PlayerTeamPermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NewsPost> NewsPost { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkoutPost> WorkoutPosts { get; set; }
    }
}
