//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutLog.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerTeamPermissions
    {
        public int Id { get; private set; }
        public int WorkoutPost { get; set; }
        public int NewsPost { get; set; }
        public int ManageMembers { get; set; }
    
        public virtual Player Players { get; set; }
        public virtual Team Teams { get; set; }
    }
}
